# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a050900891ef7c08a9de478fe792ee573d10a8b4b73d34d2876e87e9289702b44b00fbcd1279acc7b153de54b051f54b8afb75ee84187bf551596433e831cd3

test:
  secret_key_base: 85647b7b994bfa22599dd24f2f5f7d55b679fcc93dfc822d2e46eb3351a532882827daee4a12de5a8140d4be893fd0bbefeee783957281f1fa78d6f0001790b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
